# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2024-03-03 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20240303_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 13, 41, 51, 744491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 13, 41, 51, 744491, tzinfo=utc)),
        ),
    ]
